### ISSUE TITLE
Build sdcard image take more than 4 hours

### ISSUE THREAD

**Issue by rick-yhchen1013** [analogdevicesinc/aditof-sdk-rework#204] opened 2021-11-18 02:46 UTC
By executing the runme.sh in sdcard-images-utils/nxp
It takes long time to finish the build of image, the deboostrap looks quite slow.
Both of the cpu and iostat usage looks low.

The test machine is a Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz with Ubuntu 18.04 installed.

**Comment by btogorean** [comment] 2021-11-18 12:01
debootstrap is known to be very slow. There are some patches to speed it up but not merged yet : https://bugs.launchpad.net/ubuntu/+source/debootstrap/+bug/1126314
On our case the problem is even more visible because we have "cross-debootstrapping" which is cross architecture bootstrapping through QEMU emulator for ARM.

**Comment by rick-yhchen1013** [comment] 2021-11-19 01:51
Thanks for your reply.

Is the whole build time on your side also more than 1 hour?
I found it reduce total time less than 30 minutes if I change the filesystem to ext4 and mount the loop device with -o barrier=0.

@@ -271,8 +272,12 @@ function main() {
   # create 1GB ext2 image
   dd if=/dev/zero of=rootfs.ext2 bs=1M count=3000
   mkdir -p ${ROOTFS_TMP}
-  mkfs.ext2 rootfs.ext2
-  sudo mount -o loop rootfs.ext2 ${ROOTFS_TMP}
+  mkfs.ext4 rootfs.ext2
+  sudo mount -o loop -o barrier=0 rootfs.ext2 ${ROOTFS_TMP}

**Comment by btogorean** [comment] 2021-11-19 08:02
Yes, it is taking around 2 hours on build server.
But thank you for optimisation suggestion. We'll check it out and merge it in master.

**Comment by rick-yhchen1013** [comment] 2021-11-20 12:17
If this change is acceptable, I can launch a pull request and we can have a review there.

**Closed** 2021-11-24 03:45 UTC

**Comment by rick-yhchen1013** [comment] 2021-11-24 03:46
The pull request #208 is adopted so that we can close this issue
